apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
resources:
- https://raw.githubusercontent.com/linkerd/linkerd-examples/b7c0eba5953e0b006a54d2e566e88a05b4a880a8/gitops/resources/linkerd/trust-anchor.yaml
- https://raw.githubusercontent.com/linkerd/linkerd-examples/b7c0eba5953e0b006a54d2e566e88a05b4a880a8/gitops/resources/linkerd/trust-issuer.yaml
