apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echoserver
resources:
# ref: https://ealenn.github.io/Echo-Server/pages/quick-start/kubernetes.html
- https://raw.githubusercontent.com/Ealenn/Echo-Server/f44dd5d1333630b1135d837e4c5accdaf5225070/docs/examples/echo.kube.yaml