apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/core-install.yaml
- projects.yaml
- apps/argocd.yaml
- apps/nginx-ingress.yaml
- apps/cert-manager.yaml
#- apps/linkerd-bootstrap.yaml
#- apps/linkerd.yaml
#- apps/linkerd-emojivoto.yaml
#- apps/crossplane.yaml