apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: argocd
spec:
  destinations:
  - namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/kzap/k8s-local.git