apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-emojivoto
  namespace: argocd
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: default
  source:
    path: linkerd/emojivoto
    repoURL: https://github.com/kzap/k8s-local.git
  syncPolicy:
    automated: {}
    syncOptions: # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
