apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: core-services
  source:
    path: nginx-ingress
    repoURL: https://github.com/kzap/k8s-local.git
