apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: core-services
  source:
    chart: sealed-secrets
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: 1.10.3
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions: # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
