apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: github-repo
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: github-credentials.json
    env:
      name: GITHUB_TOKEN
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: github-credentials
      key: token
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      provider "github" {
        owner = "kzap"
      }

      // Modules _must_ use remote state. The provider does not persist state.
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }

        required_providers {
          github = {
            source  = "integrations/github"
            version = "~> 4.0"
          }
        }
      }